### ISSUE TITLE
Error: Error: Command failed: git push heroku HEAD:refs/heads/main --force

### ISSUE THREAD

**Issue by PersesTitan** [Couch-Coders/9th-soccer-BE#3]
# 내용
Error: Command failed: heroku create soccer-community 와 같은 에러는 해결하였지만 ...
Error: Error: Command failed: git push heroku HEAD:refs/heads/main --force [링크](https://github.com/Couch-Coders/9th-soccer-BE/runs/7376846504?check_suite_focus=true) 와 같은 에러가 추가 발생하였습니다. 
#1 의 path 제거와 **akhileshns/heroku-deploy@v3.12.12**를 변경하여 다른 에러로 바뀌었습니다.

# P.S.
관련 에러를 찾아보니 자동 배포를 이용하여 대부분 해결해서 해결법을 찾기가 어려운 상황입니다...

**Comment by yourhrh** [comment]
system.properties 파일 하나 만들어주시고 
java.runtime.version=17 넣어주세요
로그 쭉 위로 올리시면 java version이 8로 설정되서 안되네요 
첫 수업때 알려드리긴 했는데 놓쳤을 수 있어요

**Comment by PersesTitan** [comment]
> system.properties 파일 하나 만들어주시고 java.runtime.version=17 넣어주세요 로그 쭉 위로 올리시면 java version이 8로 설정되서 안되네요 첫 수업때 알려드리긴 했는데 놓쳤을 수 있어요

저런... 프로퍼티 파일을 추가로 해야되는 거였군요... 한번 해보겠습니다.
